# variables:

#stages:
#  - build
#  - test
#  - analyze

default:
  image: roife/compiler-judger

update_std: # Update the compiler of THU/USTC & Run test
  when: manual
  script:
    - bash scripts/fetch_thu.sh
    - bash scripts/fetch_ustc.sh
    - bash scripts/fetch_ustc_no_vec.sh
    - bash scripts/fetch_sysyruntimelibrary.sh
    - python3 scripts/test_std.py
  cache:
    paths:
      - build/bin/*
      - build/include/*
      - build/lib/*
      - build/log/*
      - build/test_results/*
  artifacts:
    paths:
      - build/log/*
  tags:
    - arm
  timeout: 3h

#build_compiler:  # build NSFW

#test_all_cases:   # Test & Judge all testcases

#analyze_results: # analyze results

