# variables:

run_func_1:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/functional_test/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_functional.sh
  tags:
    - x86
  timeout: 10m

run_func_thu:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/thu_test/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_thu.sh
  tags:
    - x86
  timeout: 10m

run_perf_1:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/performance_test/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_performance.sh
  tags:
    - x86
  timeout: 120m

run_perf_1_comp:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/performance_test/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_performance.sh
  tags:
    - x86
  timeout: 15m

run_perf_1_pro:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/performance_test_pro/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_performance_pro.sh
  tags:
    - x86
  timeout: 30m

run_func_2:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/functional_test/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_functional2.sh
  tags:
    - x86
  timeout: 3m

run_perf_2:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/performance_test/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_performance2.sh
  tags:
    - x86
  timeout: 10m

run_perf_2_pro:
  when: manual
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv testcases/performance_test_pro/* testcases/
    - bash scripts/server_scripts/build_ayame.sh
    - bash scripts/send_to_pi_performance2_pro.sh
  tags:
    - x86
  timeout: 30m

